version: "3.4"
services:
 db:
  image: postgres:13
  ports: 
    - "5432:5432"
  environment:
      POSTGRES_DB: dimpe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      
 api:
  build: 
    context: .
    target: development
  volumes:
    - ./:/usr/src/app
    - /usr/src/app/node_modules
  ports: 
    - 3030:3030
  command: ["./wait-for-it.sh", "db:5432", "--", "npm", "run", "start"] 
