version: "3.4"
services:
 db:
  image: postgres:16
  ports: 
    - "5432:5432"
  environment:
      POSTGRES_DB: nodedeploy_pg_eo5k
      POSTGRES_USER: nodedeploy_pg_eo5k_user
      POSTGRES_PASSWORD: cRKjndhlN9ytUeFJlfj2VuzvK9llQOFP
      
 api:
  build: 
    context: .
    target: development
  volumes:
    - ./:/usr/src/app
    - /usr/src/app/node_modules
  ports: 
    - 3030:3030
  command: ["./wait-for-it.sh", "db:5432", "--", "npm", "run", "start"] 
